version: '3.8'

services:
  ai-link-scraper-daemon:
    build: .
    container_name: ai-link-scraper-daemon
    restart: unless-stopped
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - MAX_LINKS_PER_RUN=${MAX_LINKS_PER_RUN:-10}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./summaries:/app/summaries
      - ./.env:/app/.env:ro
    command: ["python", "daemon.py", "--interval", "60"]
    healthcheck:
      test: ["CMD", "python", "daemon.py", "--test"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s

  # Optional: Add a one-shot service for manual runs
  ai-link-scraper-manual:
    build: .
    container_name: ai-link-scraper-manual
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - MAX_LINKS_PER_RUN=${MAX_LINKS_PER_RUN:-10}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./summaries:/app/summaries
      - ./.env:/app/.env:ro
    profiles:
      - manual  # Only run when explicitly specified
    command: ["python", "main.py", "--send-to-slack", "--verbose"]
