# Fly.io Configuration
app = "ai-link-scraper"
primary_region = "ewr"

[build]
  image = "python:3.11-slim"

[deploy]
  strategy = "rolling"

[env]
  PORT = "8080"
  PYTHONPATH = "."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[processes]
  app = "gunicorn website.app:app --host 0.0.0.0 --port 8080"

[[statics]]
  guest_path = "/app/website/static"
  url_prefix = "/static/"
