#!/bin/bash

# Script to set up environment variables for Vercel deployment
echo "🔧 Setting up AI Link Scraper environment variables for Vercel..."

echo "ℹ️  You can add environment variables in two ways:"
echo ""
echo "1. Via Vercel CLI (recommended):"
echo "   vercel env add SLACK_BOT_TOKEN"
echo "   vercel env add OPENAI_API_KEY" 
echo "   vercel env add SLACK_CHANNEL_ID"
echo ""
echo "2. Via Vercel Dashboard:"
echo "   - Go to: https://vercel.com/arjan-2388s-projects/ai-link-scraper/settings/environment-variables"
echo "   - Add each variable with values from your .env file"
echo ""
echo "📝 Required environment variables:"
echo "   SLACK_BOT_TOKEN      - Your Slack bot token"
echo "   OPENAI_API_KEY       - Your OpenAI API key"
echo "   SLACK_CHANNEL_ID     - Your Slack channel ID"
echo "   OUTPUT_FOLDER        - summaries (default)"
echo "   MAX_LINKS_PER_RUN    - 99999 (default)"
echo ""
echo "⚠️  IMPORTANT: Never commit .env files to Git!"
echo "    Your secrets should only be stored in Vercel's environment variables."
echo ""
echo "🔄 After adding environment variables, redeploy with:"
echo "   vercel --prod"
