name: Daily AI Link Scraper

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9:00 AM UTC
  workflow_dispatch:

jobs:
  daily-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install schedule
          pip install -r requirements.txt || true
      - name: Set up environment variables
        run: |
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> .env
          echo "SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "SUMMARY_MAX_LENGTH=500" >> .env
      - name: Run daily scheduler
        run: |
          python daily_scheduler.py --run-now
