name: AI Link Scraper - Mention Response

on:
  schedule:
    # Check for mentions every 15 minutes during extended hours (7 AM - 10 PM EST = 12 PM - 3 AM UTC)
    - cron: '*/15 12-23 * * *'  # 12 PM - 11:45 PM UTC
    - cron: '*/15 0-3 * * *'    # 12 AM - 3:45 AM UTC (next day)
  workflow_dispatch: # Manual trigger
  repository_dispatch:
    types: [check-mentions] # Can be triggered externally

jobs:
  check-mentions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Check for mentions across all channels
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Checking for mentions across all accessible channels..."
        python main.py --check-all-channels --verbose
        echo "Mention check completed!"
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: mention-check-logs-${{ github.run_number }}
        path: logs/
        retention-days: 7
