name: AI Link Scraper - All Message Scraper

on:
  schedule:
    # Scrape all messages every 10 minutes (1:00, 1:10, 1:20, 1:30, etc.)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Manual trigger
  repository_dispatch:
    types: [check-mentions] # Can be triggered externally

jobs:
  check-mentions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Scrape all messages across all channels
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Scraping all messages across all accessible channels..."
        python main.py --check-all-channels --verbose
        echo "All message scraping completed!"
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: all-message-scrape-logs-${{ github.run_number }}
        path: logs/
        retention-days: 7
